FROM ubuntu:22.04


# 安装必要软件
RUN apt-get update && \
    apt-get install -y \
    ca-certificates \
    curl \
    wget \
    vim \
    nano \
    git \
    openssh-client \
    openssh-server \
    sudo \
    iputils-ping \
    xz-utils \
    bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 更新
RUN apt-get update && apt-get upgrade -y 

# 默认进入 shell
CMD ["/bin/bash"]



# 构建镜像
# docker build -t ubuntu22.04 .
# 构建多平台镜像load
# docker buildx build --platform linux/amd64,linux/arm64 --load -t ubuntu22.04:soft .
# 构建多平台镜像push
# docker buildx build --platform linux/amd64,linux/arm64 --push -t ubuntu22.04 .
# 运行容器
# docker run -it --rm ubuntu22.04