FROM cyhfch/userssh
LABEL version="20260604-v1.0.0"


ARG USERNAME=user
ARG GROUPNAME=user
ARG UID=1000
ARG GID=1000

COPY scripts/create_user.sh /tmp/create_user.sh
RUN chmod +x /tmp/create_user.sh && \
    /tmp/create_user.sh "$USERNAME" "$GROUPNAME" "$UID" "$GID"

# 拷贝默认启动脚本
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER ${USERNAME}
WORKDIR /home/${USERNAME}

ENTRYPOINT ["/entrypoint.sh"]